version: '2'
services:
  cloudsmartcbm-app:
    image: cloudsmartcbm.azurecr.io/cloudsmartcbm
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger,tls
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://cloudsmartcbm-postgresql:5432/CloudSmartCBM
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://cloudsmartcbm-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://cloudsmartcbm-elasticsearch:9200
      - SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS=kafka:9092
      - API_REQUEST_SETTINGS_HEADERS_AUTHORIZATION=338D1A36-A7F7-4459-A208-8FDFD79D88DC
      - API_POLL_OVERALL_ENABLED=true
    ports:
      - ${HTTPS_PORT}:443
  cloudsmartcbm-postgresql:
    image: postgres:11.4
    # volumes:
    #     - ~/volumes/CloudSmartCBM/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=CloudSmartCBM
      - POSTGRES_PASSWORD=
    ports:
      - ${POSTGRE_PORT}:5432
  cloudsmartcbm-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    # volumes:
    #     - ~/volumes/CloudSmartCBM/elasticsearch/:/usr/share/elasticsearch/data/
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - 'ES_JAVA_OPTS=-Xms1024m -Xmx1024m'
      - 'discovery.type=single-node'
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - 2181:2181
  kafka:
    image: confluentinc/cp-kafka:5.3.0
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - ${KAFKA_PORT}:9092
